# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9b2fb1c136808ae24610074ab2c91e08d877ab1615e86a012c5dcfe3996350944e549e33672192b1f52776862d95dfc2d84927975b2c04ce7a9bee1460bd3c

test:
  secret_key_base: 23015f0db88734816741e3ad4470ef516e9994a4d213876fe3336d6923bc9e9674c3ba93d110a4494ae54d388d114e857060e7cacaa51164b99c5824c53ad28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
